### PR TITLE
Avoid deleting files while iterating ReadDir

### PR DESCRIPTION
**Pull request by WhyNotHugo**
[Deleting a file while itearting a read_dir is undefined behaviour][1]:

> If a file is removed from or added to the directory after the most
> recent call to opendir() or rewinddir() whether a subsequent call to
> readdir() returns an entry for that file is unspecified.

[1]: https://pubs.opengroup.org/onlinepubs/9699919799/functions/readdir.html

Fixes: https://github.com/coreos/cargo-vendor-filterer/issues/60

### CODE REVIEW

**Comment by WhyNotHugo** [comment]
@cgwalters I see you've merged a few PRs here recently, any comments on this one? It's blocking my usage of `cargo-vendor-filterer` for some releases.

**Review by cgwalters — APPROVED** [review]
Thanks!

**Comment by WhyNotHugo** [comment]
Mind pushing a new tag/release for this one?

I'm looking to use this in my CI and I'd rather use distribution packages than build from source on each run :)

**Comment by cgwalters** [comment]
Sure, mind stamping  https://github.com/coreos/cargo-vendor-filterer/pull/62 ?

**Comment by cgwalters** [comment]
Released https://crates.io/crates/cargo-vendor-filterer/0.5.9

**Comment by WhyNotHugo** [comment]
Thanks! I've [pushed a package to Alpine's `testing` repo](https://github.com/coreos/cargo-vendor-filterer/pull/61) so I can use this in my CI pipelines for publishing tarballs.

**Pull request merged**
